apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-dev
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/sklyarov1998/sela-final
    targetRevision: feature_Daniel
    path: Chart/templates
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-prod
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/sklyarov1998/sela-final
    targetRevision: feature_Daniel
    path: Chart/templates
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

