apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-deployment
  labels:
    app: phonebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook

    spec:
      containers:
        - name: phonebook-app
          image: shaharnadler/phonebook:0.50
          ports:
            - containerPort: 5000

          env:
            - name: GCP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password

---
apiVersion: v1
kind: Service
metadata:
  name: phonebook-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 5000
  selector:
    app: phonebook
