apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}-deployment
  labels:
    app: {{ .Values.app_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - name: {{ .Values.app_name }}-app
          image: shaharnadler/{{ .Values.app_name }}:latest
          ports:
            - containerPort: 5000
          env:
            - name: GCP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 5000
  selector:
    app: {{ .Values.app_name }}
